image: docker:stable

stages:
  - build-url-shortener
  - test-url-shortener
  - build-heroku

variables:
  IMAGE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}

build:
  stage: build-url-shortener
  services:
    - docker:19.03.11-dind
  variables:
    DOCKER_DRIVER: overlay2
    DB_NAME: url-shortener-db
  script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $IMAGE:$CI_COMMIT_SHORT_SHA || true
    - docker build
        --cache-from $IMAGE:$CI_COMMIT_SHORT_SHA
        --tag $IMAGE:$CI_COMMIT_SHORT_SHA
        --file ./services/url-shortener/Dockerfile.prod
        "./services/url-shortener"
    - docker push $IMAGE:$CI_COMMIT_SHORT_SHA

test-url-shortener:
  stage: test-url-shortener
  image: $IMAGE:$CI_COMMIT_SHORT_SHA
  services:
    - postgres:12.3-alpine
  variables:
    POSTGRES_DB: url_shortener_test
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: ""
    POSTGRES_HOST_AUTH_METHOD: trust
    DATABASE_TEST_URL: postgres://runner@postgres.11432/url_shortener_test
    DB_NAME: postgres
    NIM_ENV: testing
  script:
    - cd /usr/src/app
    - nimble c -ry tests/database_test.nim

build-heroku:
  stage: build-heroku
  services:
    - docker:19.03.11-dind
  variables:
    DOCKER_DRIVER: overlay2
    HEROKU_APP_NAME: obscure-chamber-78463
    HEROKU_REGISTRY_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/web
  script:
    - apk add --no-cache curl
    - chmod +x ./release.sh
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $IMAGE:$CI_COMMIT_SHORT_SHA:build || true
    - docker pull $IMAGE:$CI_COMMIT_SHORT_SHA:deploy || true
    - docker build
        --target build
        --cache-from $IMAGE:$CI_COMMIT_SHORT_SHA:build
        --tag $IMAGE:$CI_COMMIT_SHORT_SHA:build
        --file ./Dockerfile.deploy
        "."
    - docker build
        --target deploy
        --cache-from $IMAGE:$CI_COMMIT_SHORT_SHA:deploy
        --tag $IMAGE:$CI_COMMIT_SHORT_SHA:deploy
        --tag $HEROKU_REGISTRY_IMAGE
        --file ./Dockerfile.deploy
        "."
    - docker push $IMAGE:$CI_COMMIT_SHORT_SHA:build
    - docker push $IMAGE:$CI_COMMIT_SHORT_SHA:deploy
    - echo -n $HEROKU_AUTH_TOKEN | docker login -u _ --password-stdin registry.heroku.com
    - docker push $HEROKU_REGISTRY_IMAGE
    - ./release.sh
