image: docker:stable

stages:
  - build-url-shortener
  - test-url-shortener
  - build-heroku

variables:
  IMAGE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}

build:
  stage: build-url-shortener
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DB_NAME: url-shortener-db
  script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $IMAGE:url-shortener-latest || true
    - docker build
        --cache-from $IMAGE:url-shortener-latest
        --tag $IMAGE:url-shortener-latest
        --file ./services/url-shortener/Dockerfile.prod
        "./services/url-shortener"
    - docker push $IMAGE:url-shortener-latest

test-url-shortener:
  stage: test-url-shortener
  image: $IMAGE:url-shortener-latest
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: url_shortener_test
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: ""
    DATABASE_TEST_CONN: postgres://runner@postgres:5432/url_shortener_test
    DB_NAME: postgres
    NIM_ENV: testing
  script:
    - cd /usr/src/app
    - nimble c -ry tests/database_test.nim

build-heroku:
  stage: build-heroku
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    HEROKU_APP_NAME: obscure-chamber-78463
    HEROKU_REGISTRY_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/web
  script:
    - apk add --no-cache curl
    - chmod +x ./release.sh
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $IMAGE:url-shortener-deploy || true
    - docker build
        --cache-from $IMAGE:url-shortener-deploy
        --tag $IMAGE:url-shortener-deploy
        --tag $HEROKU_REGISTRY_IMAGE
        --file ./Dockerfile.deploy
        "."
    - docker push $IMAGE:url-shortener-deploy
    - echo -n $HEROKU_AUTH_TOKEN | docker login -u _ --password-stdin registry.heroku.com
    - docker push $HEROKU_REGISTRY_IMAGE
    - ./release.sh
