image: docker:stable

stages:
  - build-url-shortener
  - test-url-shortener

variables:
  IMAGE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}

build:
  stage: build-url-shortener
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $IMAGE:url-shortener-latest || true
    - docker build
        --cache-from $IMAGE:url-shortener-latest
        --tag $IMAGE:url-shortener-latest
        --file ./services/url-shortener/Dockerfile.prod
        "./services/url-shortener"
    - docker push $IMAGE:url-shortener-latest

test-url-shortener:
  stage: test-url-shortener
  image: $IMAGE:url-shortener-latest
  services:
    - docker:dind
  script:
    - cd /usr/src/app
    - nimble c -ry tests/database_test.nim
