version: '2.4'

services:

  url-shortener:
    build:
      context: ./services/url-shortener
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - './services/url-shortener:/usr/src/app:delegated'
    ports:
      - 5001:7777
    environment:
      - NIM_ENV=development
      - PORT=7777
      - DB_NAME=url-shortener-db
      - DATABASE_URL=postgresql://postgres:postgres@url-shortener-db:5432/url_shortener_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@url-shortener-db:5432/url_shortener_test
    depends_on:
      url-shortener-db:
        condition: service_healthy

  url-shortener-db:
    build:
      context: ./services/url-shortener/src/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
