version: '2.4'

services:

  url-shortener:
    build:
      context: ./services/url-shortener
      dockerfile: Dockerfile
    volumes:
      - './services/url-shortener:/usr/src/app:delegated'
    ports:
      - 5001:5000
    environment:
      - NIM_ENV=development
      - DB_NAME=url-shortener-db
      - DATABASE_DEV_CONN=postgresql://postgres:postgres@url-shortener-db:5432/url_shortener_dev
      - DATABASE_TEST_CONN=postgresql://postgres:postgres@url-shortener-db:5432/url_shortener_test
      - DATABASE_PROD_CONN=postgresql://postgres:postgres@url-shortener-db:5432/url_shortener_prod
    entrypoint: ['/usr/src/app/entrypoint.sh']
    depends_on:
      - url-shortener-db

  url-shortener-db:
    build:
      context: ./services/url-shortener/src/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
